// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGlIWDsk_C1xRnvfAljgUGOSx5PylPK-c',
    appId: '1:996601875243:web:f838aaf9f2b9bdea58d36e',
    messagingSenderId: '996601875243',
    projectId: 'restofinder-e0a65',
    authDomain: 'restofinder-e0a65.firebaseapp.com',
    storageBucket: 'restofinder-e0a65.appspot.com',
    measurementId: 'G-1B2XC0SSBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEIMiiPowKiLj0DsccTtajcgix8RDjCMc',
    appId: '1:996601875243:android:ca13f2d8c006947058d36e',
    messagingSenderId: '996601875243',
    projectId: 'restofinder-e0a65',
    storageBucket: 'restofinder-e0a65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXnvFldXfdm8RswOvTuAkR4ke9aqQ88a0',
    appId: '1:996601875243:ios:44cdb8e25a29ec7658d36e',
    messagingSenderId: '996601875243',
    projectId: 'restofinder-e0a65',
    storageBucket: 'restofinder-e0a65.appspot.com',
    iosBundleId: 'com.example.restoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXnvFldXfdm8RswOvTuAkR4ke9aqQ88a0',
    appId: '1:996601875243:ios:b1a4f3a008d0bcf058d36e',
    messagingSenderId: '996601875243',
    projectId: 'restofinder-e0a65',
    storageBucket: 'restofinder-e0a65.appspot.com',
    iosBundleId: 'com.example.restoapp.RunnerTests',
  );
}
